=== Me8mer/NPRG036-Data-Formats/HW3/xml/schemas/schema-2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
	
	<xs:complexType name="EShopType">
		<xs:sequence>
			<xs:element name="Name" type="LangStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="URL" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Icon" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CartType">
		<xs:sequence>
			<xs:element name="ItemCount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TotalPrice" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ItemType">
		<xs:sequence>
			<xs:element name="Name" type="LangStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Price" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Description" type="LangStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Available" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="InStock"/>
						<xs:enumeration value="OutOfStock"/>
						<xs:enumeration value="PreOrder"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PromoImages" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="EShop" type="EShopType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Cart" type="CartType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

		<xs:element name="ItemsHierarchy">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Item" type="ItemType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="LangStringType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="xml:lang" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== Me8mer/NPRG036-Data-Formats/HW3/xml/data/data-2.xml
<ItemsHierarchy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:noNamespaceSchemaLocation="./../schemas/schema-2.xsd">
  
  <EShop>
    <Name xml:lang="en">Goth Fridges</Name>
    <URL>https://www.gothcorp.com/shop/fridges</URL>
    <Icon>https://example.org/images/fridge.png</Icon>
    <Item>
      <Name xml:lang="en">Cold Cold Fridge</Name>
      <Price>999.99</Price>
      <Description xml:lang="en">Perfect to keep your vegetables fresh.</Description>
      <Available>InStock</Available>
      <PromoImages>https://example.org/images/fridge_front.png</PromoImages>
      <PromoImages>https://example.org/images/fridge_side.png</PromoImages>
      <PromoImages>https://example.org/images/fridge_open.png</PromoImages>
    </Item>
  </EShop>

  <EShop>
    <Name xml:lang="en">Wayne's Gains</Name>
    <URL>https://www.waynesgains.com</URL>
    <Icon>https://example.org/images/protein.png</Icon>
    <Item>
      <Name xml:lang="en">Bat-Protein</Name>
      <Price>50.49</Price>
      <Description xml:lang="en">Keep out of reach of penguins.</Description>
      <Available>OutOfStock</Available>
      <PromoImages>https://example.org/images/protein_top.png</PromoImages>
      <PromoImages>https://example.org/images/protein_side.png</PromoImages>
      <PromoImages>https://example.org/images/protein_inside.png</PromoImages>
    </Item>
  </EShop>

  <EShop>
    <Name xml:lang="en">Lex Rides</Name>
    <URL>https://www.lexcorp.com/vehicles/shop</URL>
    <Icon>https://example.org/images/car.png</Icon>
    <Item>
      <Name xml:lang="en">SuperVan</Name>
      <Price>10024.99</Price>
      <Description xml:lang="en">Made on Earth by humans.</Description>
      <Available>PreOrder</Available>
      <PromoImages>https://example.org/images/van_front.png</PromoImages>
      <PromoImages>https://example.org/images/van_back.png</PromoImages>
      <PromoImages>https://example.org/images/van_leather_seats.png</PromoImages>
    </Item>
  </EShop>

</ItemsHierarchy>
