=== Me8mer/NPRG036-Data-Formats/HW3/xml/schemas/schema-1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
	
	<xs:complexType name="OwnerType">
		<xs:sequence>
			<xs:element name="Name" type="LangStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="CompanyID" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="EShop" type="EShopType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="EShopType">
		<xs:sequence>
			<xs:element name="Name" type="LangStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="URL" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Icon" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Account" type="AccountType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AccountType">
		<xs:sequence>
			<xs:element name="Login" type="LangStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Cart" type="CartType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CartType">
		<xs:sequence>
			<xs:element name="ItemCount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TotalPrice" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="EShopHierarchy">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Owner" type="OwnerType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="LangStringType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="xml:lang" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== Me8mer/NPRG036-Data-Formats/HW3/xml/data/data-1.xml
<EShopHierarchy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:noNamespaceSchemaLocation="./../schemas/schema-1.xsd">
  
  <Owner>
    <Name xml:lang="en">Goth Corp</Name>
    <CompanyID>FR33Z3</CompanyID>
    <EShop>
      <Name xml:lang="en">Goth Fridges</Name>
      <URL>https://www.gothcorp.com/shop/fridges</URL>
      <Icon>https://example.org/images/fridge.png</Icon>
      <Account>
        <Login xml:lang="en">Boyoyoyle</Login>
        <Password>nothing2c</Password>
        <Cart>
          <ItemCount>1</ItemCount>
          <TotalPrice>999.99</TotalPrice>
        </Cart>
      </Account>
    </EShop>
  </Owner>

  <Owner>
    <Name xml:lang="en">Wayne Enterprises</Name>
    <CompanyID>8UTTL3R</CompanyID>
    <EShop>
      <Name xml:lang="en">Wayne's Gains</Name>
      <URL>https://www.waynesgains.com</URL>
      <Icon>https://example.org/images/protein.png</Icon>
      <Account>
        <Login xml:lang="en">BatMan4Ever</Login>
        <Password>AlfredDaButtler</Password>
        <Cart>
          <ItemCount>1</ItemCount>
          <TotalPrice>50.49</TotalPrice>
        </Cart>
      </Account>
    </EShop>
  </Owner>

  <Owner>
    <Name xml:lang="en">Lex Crop</Name>
    <CompanyID>HAT3R_1</CompanyID>
    <EShop>
      <Name xml:lang="en">Lex Rides</Name>
      <URL>https://www.lexcorp.com/vehicles/shop</URL>
      <Icon>https://example.org/images/car.png</Icon>
      <Account>
        <Login xml:lang="en">SuperLoser</Login>
        <Password>1a1a1A</Password>
        <Cart>
          <ItemCount>1</ItemCount>
          <TotalPrice>10024.99</TotalPrice>
        </Cart>
      </Account>
    </EShop>
  </Owner>

</EShopHierarchy>
